name: Build LaTeX PDFs

on:
    push:
        tags:
            - "v*" # run only on version tags (e.g. v1.0.0)

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: texlive/texlive:latest

        steps:
            # 1 – Checkout the repository (full history so tags are present)
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            # 2 – Mark the workspace as safe for Git
            - name: Configure Git
              run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            # 3 – Make sure main is current (autostash handles any build artefacts)
            - name: Update main
              run: |
                  git checkout main
                  git pull --rebase --autostash origin main

            # 4 – Determine the latest tag (fallback to v0.0.0)
            - name: Get latest tag
              run: |
                  TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
                  echo "Latest tag: $TAG"
                  echo "$TAG" > version.tex
                  echo "VERSION=$TAG" >> "$GITHUB_ENV"

            # 5 – Compile the manual (rerun for cross-references if needed)
            - name: Compile manual
              run: |
                  set -e
                  for i in 1 2 3; do
                    xelatex -interaction=nonstopmode prismaid_manual.tex || true
                    grep -q "Rerun to get cross-references right" prismaid_manual.log || break
                    echo "Re-running xelatex to fix cross-references…"
                  done

            # 6 – Commit and push the generated PDF + version file
            - name: Commit and push artefacts
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.name  "GitHub Action"
                  git config --global user.email "action@github.com"
                  git add prismaid_manual.pdf version.tex
                  git diff --cached --quiet || git commit -m "Update PDF and version info"
                  git push

            # 7 – Attach the PDF to the release
            - name: Upload PDF to release
              uses: softprops/action-gh-release@v1
              with:
                  files: prismaid_manual.pdf
                  tag_name: ${{ env.VERSION }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
